#!/bin/bash
# ~/.bash_aliases
#
# vim: set filetype=sh:

# David J Galvan Jr
# Created:          Thu 28 Jul 2011 09:38:47 PM EST
# Modified:         Sun 01 Oct 2017 06:11:26 PM DST
# Last modified:    Wed Feb 21 13:50:40 2018

#-----------------------------------------------------------------------------#
# directory shortcuts
#-----------------------------------------------------------------------------#

###############################################################################
# Aliases #####################################################################

#-----------------------------------------------------------------------------#
# general
#-----------------------------------------------------------------------------#
alias ce='crontab -e'
alias v='$EDITOR -n'
alias vl='/usr/share/vim/vim73/macros/less.sh'
alias diff='colordiff'
alias cp='cp --interactive --verbose'
alias mv='mv --interactive --verbose'
alias rm='rm -I --verbose'
alias ln='ln --interactive'
alias grep='grep --color=auto'
alias mkdir='mkdir --parents --verbose'
alias xrdb-merge='xrdb -merge ~/.Xresources && exit'
alias mm='morc_menu'
alias lock='blurlock && sleep 10; xset dpms force off'
alias make50='make CC=clang CFLAGS="-ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow" LDLIBS="-lcs50 -lm"'
# print external IP Adress using lynx
alias myip='lynx --dump http://whatismyip.org'
alias web='lynx -vikeys https://www.google.com'

#-----------------------------------------------------------------------------#
# moving up directory levels
#-----------------------------------------------------------------------------#
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

#-----------------------------------------------------------------------------#
# ls aliases
#-----------------------------------------------------------------------------#

# ls colors 
alias ls='ls --human-readable --indicator-style=slash --classify --color=auto'

alias ldir='ls -lhA |grep ^d'   # List directories
alias lfiles='ls -lhA |grep ^-' # List files

alias ll='ls -l'                # List files and directories in long format
alias la='ls -A'                # List all files and directories (inc. hidden)
alias lla='ls -lA'              # List all (inc. hidden) in long format
alias lx='ls -lBX'              # Sort by extension
alias lz=' ls -lrS '            # Sort by size
alias lt='ls -lrt'              # Sort by date

alias ldu='ls -l /dev/disk/by-uuid'  # List all disk/partitions by uuid
alias ldl='ls -l /dev/disk/by-label' # List all disk/partitions by label

#-----------------------------------------------------------------------------#
# search aliases
#-----------------------------------------------------------------------------#
alias lss='ls -lARt | grep $1'                      # ls search recursively
alias pss='ps -ef | grep -v grep | grep $1'         # processes search

#-----------------------------------------------------------------------------#
# aria2c aliases
#-----------------------------------------------------------------------------#
alias aria='aria2c --max-connection-per-server=4 --allow-overwrite=true \
    --file-allocation=falloc --log-level=error --summary-interval=120'

#-----------------------------------------------------------------------------#
# aliases to edit dotfiles --makes for easy v[tab][tab] of my favs
#-----------------------------------------------------------------------------#
alias vbashrc="$EDITOR -n ~/.bashrc"
alias valiases="$EDITOR -n ~/.aliases"
alias vfunctions="$EDITOR -n ~/.bash_functions"
alias vvimrc="$EDITOR -n ~/.vim/vimrc"
alias vxresources="$EDITOR -n ~/.Xresources"
alias vxinitrc="$EDITOR -n ~/.xinitrc"
alias vtmuxconf="$EDITOR -n ~/.tmux.conf"
alias vrtorrentrc="$EDITOR -n ~/.rtorrent.rc"
alias vpglcmdconf="$EDITOR -n /etc/pgl/pglcmd.conf"
alias vawesome="$EDITOR -n ~/.config/awesome/rc.lua"

#-----------------------------------------------------------------------------#
# log viewing
#-----------------------------------------------------------------------------#
alias log-pgl='less +F /var/log/pgl/pgld.log'
alias log-everything='less +F /var/log/everything.log'
alias log-messages='less +F /var/log/messages.log'
alias log-crond='less +F /var/log/crond.log'
alias log-xorg='less +F /var/log/Xorg.0.log'
alias log-auth='less +F /var/log/auth.log'

###############################################################################
# Functions
###############################################################################
ranger() {
    if [ -z "$RANGER_LEVEL" ]; then
        ranger-cd "$@"
    else
        exit
    fi
}

# Local Variables:
# mode:zsh
# End:
